# Copyright (C) 2016 iNuron NV
#
# This file is part of Open vStorage Open Source Edition (OSE),
# as available from
#
#      http://www.openvstorage.org and
#      http://www.openvstorage.com.
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License v3 (GNU AGPLv3)
# as published by the Free Software Foundation, in version 3 as it comes
# in the LICENSE.txt file of the Open vStorage OSE distribution.
#
# Open vStorage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY of any kind.


class SdkOptionMapping(object):
    disk_options_mapping = {
        "mountpoint": {
            "option": "path",
            "values": None,
            "type": str
        },
        "pool": {
            "option": "pool",
            "values": None,
            "type": str
        },
        "vol": {
            "option": "vol",
            "values": None,
            "type": str
        },
        "device": {
            "option": "device",
            "values": ["cdrom", "disk", "lun", "sata", "floppy"],
            "default": "disk",
            "type": str
        },
        "boot_order": {
            "option": "boot_order",
            "values": None,
            "type": int
        },
        "bus": {
            "option": "bus",
            "values": ["ide", "sata", "iscsi", "sata", "usb", "virtio", "xen"],
            "default": "virtio",
            "type": str
        },
        "removable": {
            "option": "removable",
            "values": ["on", "off"],
            "type": str
        },
        "readonly": {
            "option": "readonly",
            "values": ["on", "off"],
            "type": str
        },
        "shareable": {
            "option": "shareable",
            "values": ["on", "off"],
            "type": str
        },
        "size": {
            "option": "size",
            "values": None,
            "type": float
        },
        "format": {
            "option": "format",
            "values": ["raw", "qcow2", "vmdk"],
            "default": "raw",
            "type": str
        },
        "sparse": {
            "option": "sparse",
            "values": ["yes", "no"],
            "default": "yes",
            "type": str
        },
    }
    network_option_mapping = {
        "bridge": {
            "option": "bridge",
            "values": None,
            "default": None,
            "type": str
        },
        "network": {
            "option": "network",
            "values": None,
            "default": None,
            "type": str
        },
        "model": {
            "option": "model",
            "values": ["e1000", "rtl8139", "virtio"],
            "default": "e1000",
            "type": str
        },
        "mac": {
            "option": "mac",
            "values": None,
            "default": "random",
            "type": str
        },
    }

    # Generated with _generate_ostype_options
    @staticmethod
    def _generate_ostype_options():
        """
        Will generate all options based on osinfo-query os. Requires libosinfo-bin
        :return:
        """
        import subprocess
        cmd = ['osinfo-query', 'os']
        output = subprocess.check_output(cmd)
        items = {}
        for index, line in enumerate(output.splitlines()):
            print index
            if index <= 2:  # SKip first two
                continue
            line = line.replace(' ', '').split('|')
            os_type = line[0]
            os_name = line[1]
            os_version = line[2]
            os_url = line[3]
            items[os_type] = {'name': os_name, 'os_version': os_version, 'os_url': os_url}
        print items
        return items

    optype_options = {
        'openbsd5.1': {'os_version': '5.1', 'name': 'OpenBSD5.1', 'os_url': 'http://openbsd.org/openbsd/5.1'},
        'ubuntu10.04': {'os_version': '10.04', 'name': 'Ubuntu10.04LTS', 'os_url': 'http://ubuntu.com/ubuntu/10.04'},
        'fedora-unknown': {'os_version': 'unknown', 'name': 'Fedora',
                           'os_url': 'http://fedoraproject.org/fedora/unknown'},
        'ubuntu11.10': {'os_version': '11.10', 'name': 'Ubuntu11.10', 'os_url': 'http://ubuntu.com/ubuntu/11.10'},
        'opensuse-unknown': {'os_version': 'unknown', 'name': 'openSUSE',
                             'os_url': 'http://opensuse.org/opensuse/unknown'},
        'rhl4.2': {'os_version': '4.2', 'name': 'RedHatLinux4.2', 'os_url': 'http://redhat.com/rhl/4.2'},
        'rhl4.0': {'os_version': '4.0', 'name': 'RedHatLinux4.0', 'os_url': 'http://redhat.com/rhl/4.0'},
        'rhl4.1': {'os_version': '4.1', 'name': 'RedHatLinux4.1', 'os_url': 'http://redhat.com/rhl/4.1'},
        'rhel3.9': {'os_version': '3.9', 'name': 'RedHatEnterpriseLinux3Update9',
                    'os_url': 'http://redhat.com/rhel/3.9'},
        'rhel3.8': {'os_version': '3.8', 'name': 'RedHatEnterpriseLinux3Update8',
                    'os_url': 'http://redhat.com/rhel/3.8'},
        'mandriva2009.1': {'os_version': '2009.1', 'name': 'MandrivaLinux2009Spring',
                           'os_url': 'http://mandriva.com/mandriva/2009.1'},
        'mandriva2009.0': {'os_version': '2009.0', 'name': 'MandrivaLinux2009',
                           'os_url': 'http://mandriva.com/mandriva/2009.0'},
        'rhel3.5': {'os_version': '3.5', 'name': 'RedHatEnterpriseLinux3Update5',
                    'os_url': 'http://redhat.com/rhel/3.5'},
        'rhel3.4': {'os_version': '3.4', 'name': 'RedHatEnterpriseLinux3Update4',
                    'os_url': 'http://redhat.com/rhel/3.4'},
        'rhel3.7': {'os_version': '3.7', 'name': 'RedHatEnterpriseLinux3Update7',
                    'os_url': 'http://redhat.com/rhel/3.7'},
        'rhel3.6': {'os_version': '3.6', 'name': 'RedHatEnterpriseLinux3Update6',
                    'os_url': 'http://redhat.com/rhel/3.6'},
        'rhel3.1': {'os_version': '3.1', 'name': 'RedHatEnterpriseLinux3Update1',
                    'os_url': 'http://redhat.com/rhel/3.1'},
        'netbsd5.0': {'os_version': '5.0', 'name': 'NetBSD5.0', 'os_url': 'http://netbsd.org/netbsd/5.0'},
        'netbsd5.1': {'os_version': '5.1', 'name': 'NetBSD5.1', 'os_url': 'http://netbsd.org/netbsd/5.1'},
        'ubuntu5.10': {'os_version': '5.10', 'name': 'Ubuntu5.10', 'os_url': 'http://ubuntu.com/ubuntu/5.10'},
        'rhel6.4': {'os_version': '6.4', 'name': 'RedHatEnterpriseLinux6.4', 'os_url': 'http://redhat.com/rhel/6.4'},
        'sled9': {'os_version': '9', 'name': 'SUSELinuxEnterpriseDesktop9', 'os_url': 'http://suse.com/sled/9'},
        'win8.1': {'os_version': '6.3', 'name': 'MicrosoftWindows8.1', 'os_url': 'http://microsoft.com/win/8.1'},
        'rhel6.5': {'os_version': '6.5', 'name': 'RedHatEnterpriseLinux6.5', 'os_url': 'http://redhat.com/rhel/6.5'},
        'rhel3.3': {'os_version': '3.3', 'name': 'RedHatEnterpriseLinux3Update3',
                    'os_url': 'http://redhat.com/rhel/3.3'},
        'ubuntu15.10': {'os_version': '15.10', 'name': 'Ubuntu15.10', 'os_url': 'http://ubuntu.com/ubuntu/15.10'},
        'opensolaris2009.06': {'os_version': '2009.06', 'name': 'SunOpenSolaris2009.06',
                               'os_url': 'http://oracle.com/opensolaris/2009.06'},
        'opensuse11.1': {'os_version': '11.1', 'name': 'openSUSE11.1', 'os_url': 'http://opensuse.org/opensuse/11.1'},
        'rhel7.0': {'os_version': '7.0', 'name': 'RedHatEnterpriseLinux7.0', 'os_url': 'http://redhat.com/rhel/7.0'},
        'ubuntu8.10': {'os_version': '8.10', 'name': 'Ubuntu8.10', 'os_url': 'http://ubuntu.com/ubuntu/8.10'},
        'freebsd8.4': {'os_version': '8.4', 'name': 'FreeBSD8.4', 'os_url': 'http://freebsd.org/freebsd/8.4'},
        'freebsd8.3': {'os_version': '8.3', 'name': 'FreeBSD8.3', 'os_url': 'http://freebsd.org/freebsd/8.3'},
        'freebsd8.2': {'os_version': '8.2', 'name': 'FreeBSD8.2', 'os_url': 'http://freebsd.org/freebsd/8.2'},
        'freebsd8.1': {'os_version': '8.1', 'name': 'FreeBSD8.1', 'os_url': 'http://freebsd.org/freebsd/8.1'},
        'freebsd8.0': {'os_version': '8.0', 'name': 'FreeBSD8.0', 'os_url': 'http://freebsd.org/freebsd/8.0'},
        'freebsd2.0.5': {'os_version': '2.0.5', 'name': 'FreeBSD2.0.5', 'os_url': 'http://freebsd.org/freebsd/2.0.5'},
        'netbsd1.3': {'os_version': '1.3', 'name': 'NetBSD1.3', 'os_url': 'http://netbsd.org/netbsd/1.3'},
        'netbsd1.0': {'os_version': '1.0', 'name': 'NetBSD1.0', 'os_url': 'http://netbsd.org/netbsd/1.0'},
        'netbsd1.1': {'os_version': '1.1', 'name': 'NetBSD1.1', 'os_url': 'http://netbsd.org/netbsd/1.1'},
        'netbsd1.6': {'os_version': '1.6', 'name': 'NetBSD1.6', 'os_url': 'http://netbsd.org/netbsd/1.6'},
        'netbsd1.4': {'os_version': '1.4', 'name': 'NetBSD1.4', 'os_url': 'http://netbsd.org/netbsd/1.4'},
        'netbsd1.5': {'os_version': '1.5', 'name': 'NetBSD1.5', 'os_url': 'http://netbsd.org/netbsd/1.5'},
        'rhel5.3': {'os_version': '5.3', 'name': 'RedHatEnterpriseLinux5.3', 'os_url': 'http://redhat.com/rhel/5.3'},
        'ubuntu10.10': {'os_version': '10.10', 'name': 'Ubuntu10.10', 'os_url': 'http://ubuntu.com/ubuntu/10.10'},
        'rhel6.2': {'os_version': '6.2', 'name': 'RedHatEnterpriseLinux6.2', 'os_url': 'http://redhat.com/rhel/6.2'},
        'rhel5.2': {'os_version': '5.2', 'name': 'RedHatEnterpriseLinux5.2', 'os_url': 'http://redhat.com/rhel/5.2'},
        'freebsd9.2': {'os_version': '9.2', 'name': 'FreeBSD9.2', 'os_url': 'http://freebsd.org/freebsd/9.2'},
        'freebsd9.3': {'os_version': '9.3', 'name': 'FreeBSD9.3', 'os_url': 'http://freebsd.org/freebsd/9.3'},
        'freebsd9.0': {'os_version': '9.0', 'name': 'FreeBSD9.0', 'os_url': 'http://freebsd.org/freebsd/9.0'},
        'freebsd9.1': {'os_version': '9.1', 'name': 'FreeBSD9.1', 'os_url': 'http://freebsd.org/freebsd/9.1'},
        'debian4': {'os_version': '4', 'name': 'DebianEtch', 'os_url': 'http://debian.org/debian/4'},
        'winvista': {'os_version': '6.0', 'name': 'MicrosoftWindowsVista', 'os_url': 'http://microsoft.com/win/vista'},
        'opensuse13.1': {'os_version': '13.1', 'name': 'openSUSE13.1', 'os_url': 'http://opensuse.org/opensuse/13.1'},
        'freebsd3.0': {'os_version': '3.0', 'name': 'FreeBSD3.0', 'os_url': 'http://freebsd.org/freebsd/3.0'},
        'freebsd3.2': {'os_version': '3.2', 'name': 'FreeBSD3.2', 'os_url': 'http://freebsd.org/freebsd/3.2'},
        'rhel5.0': {'os_version': '5.0', 'name': 'RedHatEnterpriseLinux5.0', 'os_url': 'http://redhat.com/rhel/5.0'},
        'rhel5.11': {'os_version': '5.11', 'name': 'RedHatEnterpriseLinux5.11',
                     'os_url': 'http://redhat.com/rhel/5.11'},
        'rhel5.10': {'os_version': '5.10', 'name': 'RedHatEnterpriseLinux5.10',
                     'os_url': 'http://redhat.com/rhel/5.10'},
        'opensuse11.4': {'os_version': '11.4', 'name': 'openSUSE11.4', 'os_url': 'http://opensuse.org/opensuse/11.4'},
        'solaris11': {'os_version': '11', 'name': 'SunSolaris11', 'os_url': 'http://sun.com/solaris/11'},
        'opensuse11.0': {'os_version': '11.0', 'name': 'openSUSE11.0', 'os_url': 'http://opensuse.org/opensuse/11.0'},
        'freebsd4.2': {'os_version': '4.2', 'name': 'FreeBSD4.2', 'os_url': 'http://freebsd.org/freebsd/4.2'},
        'opensuse11.2': {'os_version': '11.2', 'name': 'openSUSE11.2', 'os_url': 'http://opensuse.org/opensuse/11.2'},
        'opensuse11.3': {'os_version': '11.3', 'name': 'openSUSE11.3', 'os_url': 'http://opensuse.org/opensuse/11.3'},
        'debian6': {'os_version': '6', 'name': 'DebianSqueeze', 'os_url': 'http://debian.org/debian/6'},
        'debian7': {'os_version': '7', 'name': 'DebianWheezy', 'os_url': 'http://debian.org/debian/7'},
        'freebsd1.0': {'os_version': '1.0', 'name': 'FreeBSD1.0', 'os_url': 'http://freebsd.org/freebsd/1.0'},
        'debian5': {'os_version': '5', 'name': 'DebianLenny', 'os_url': 'http://debian.org/debian/5'},
        'rhel5.7': {'os_version': '5.7', 'name': 'RedHatEnterpriseLinux5.7', 'os_url': 'http://redhat.com/rhel/5.7'},
        'debian3': {'os_version': '3', 'name': 'DebianWoody', 'os_url': 'http://debian.org/debian/3'},
        'rhel5.5': {'os_version': '5.5', 'name': 'RedHatEnterpriseLinux5.5', 'os_url': 'http://redhat.com/rhel/5.5'},
        'rhel5.4': {'os_version': '5.4', 'name': 'RedHatEnterpriseLinux5.4', 'os_url': 'http://redhat.com/rhel/5.4'},
        'netbsd3.0': {'os_version': '3.0', 'name': 'NetBSD3.0', 'os_url': 'http://netbsd.org/netbsd/3.0'},
        'ubuntu7.04': {'os_version': '7.04', 'name': 'Ubuntu7.04', 'os_url': 'http://ubuntu.com/ubuntu/7.04'},
        'rhel5.9': {'os_version': '5.9', 'name': 'RedHatEnterpriseLinux5.9', 'os_url': 'http://redhat.com/rhel/5.9'},
        'rhel5.8': {'os_version': '5.8', 'name': 'RedHatEnterpriseLinux5.8', 'os_url': 'http://redhat.com/rhel/5.8'},
        'mandriva2007': {'os_version': '2007', 'name': 'MandrivaLinux2007',
                         'os_url': 'http://mandriva.com/mandriva/2007'},
        'debian8': {'os_version': '8', 'name': 'DebianJessie', 'os_url': 'http://debian.org/debian/8'},
        'sled11sp1': {'os_version': '11.1', 'name': 'SUSELinuxEnterpriseDesktop11SP1',
                      'os_url': 'http://suse.com/sled/11.1'},
        'rhl1.0': {'os_version': '1.0', 'name': 'RedHatLinux1.0', 'os_url': 'http://redhat.com/rhl/1.0'},
        'win2k8': {'os_version': '6.0', 'name': 'MicrosoftWindowsServer2008', 'os_url': 'http://microsoft.com/win/2k8'},
        'sled11': {'os_version': '11', 'name': 'SUSELinuxEnterpriseDesktop11', 'os_url': 'http://suse.com/sled/11'},
        'mandrake6.0': {'os_version': '6.0', 'name': 'MandrakeLinux6.0', 'os_url': 'http://mandriva.com/mandrake/6.0'},
        'mandrake6.1': {'os_version': '6.1', 'name': 'MandrakeLinux6.1', 'os_url': 'http://mandriva.com/mandrake/6.1'},
        'freebsd7.4': {'os_version': '7.4', 'name': 'FreeBSD7.4', 'os_url': 'http://freebsd.org/freebsd/7.4'},
        'sled11sp2': {'os_version': '11.2', 'name': 'SUSELinuxEnterpriseDesktop11SP2',
                      'os_url': 'http://suse.com/sled/11.2'},
        'gnome-continuous-3.10': {'os_version': '3.10', 'name': 'GNOME3.10',
                                  'os_url': 'http://gnome.org/continuous/3.10'},
        'sled10': {'os_version': '10', 'name': 'SUSELinuxEnterpriseDesktop10', 'os_url': 'http://suse.com/sled/10'},
        'freebsd7.0': {'os_version': '7.0', 'name': 'FreeBSD7.0', 'os_url': 'http://freebsd.org/freebsd/7.0'},
        'freebsd7.1': {'os_version': '7.1', 'name': 'FreeBSD7.1', 'os_url': 'http://freebsd.org/freebsd/7.1'},
        'freebsd7.2': {'os_version': '7.2', 'name': 'FreeBSD7.2', 'os_url': 'http://freebsd.org/freebsd/7.2'},
        'freebsd7.3': {'os_version': '7.3', 'name': 'FreeBSD7.3', 'os_url': 'http://freebsd.org/freebsd/7.3'},
        'win2k12': {'os_version': '6.3', 'name': 'MicrosoftWindowsServer2012',
                    'os_url': 'http://microsoft.com/win/2k12'},
        'rhel6.0': {'os_version': '6.0', 'name': 'RedHatEnterpriseLinux6.0', 'os_url': 'http://redhat.com/rhel/6.0'},
        'ubuntu6.06': {'os_version': '6.06', 'name': 'Ubuntu6.06LTS', 'os_url': 'http://ubuntu.com/ubuntu/6.06'},
        'ubuntu13.04': {'os_version': '13.04', 'name': 'Ubuntu13.04', 'os_url': 'http://ubuntu.com/ubuntu/13.04'},
        'win98': {'os_version': '4.1', 'name': 'MicrosoftWindows98', 'os_url': 'http://microsoft.com/win/98'},
        'mandrake7.2': {'os_version': '7.2', 'name': 'MandrakeLinux7.2', 'os_url': 'http://mandriva.com/mandrake/7.2'},
        'mandrake7.1': {'os_version': '7.1', 'name': 'MandrakeLinux7.1', 'os_url': 'http://mandriva.com/mandrake/7.1'},
        'mandrake7.0': {'os_version': '7.0', 'name': 'MandrakeLinux7.0', 'os_url': 'http://mandriva.com/mandrake/7.0'},
        'rhl2.0': {'os_version': '2.0', 'name': 'RedHatLinux2.0', 'os_url': 'http://redhat.com/rhl/2.0'},
        'rhl2.1': {'os_version': '2.1', 'name': 'RedHatLinux2.1', 'os_url': 'http://redhat.com/rhl/2.1'},
        'ubuntu12.10': {'os_version': '12.10', 'name': 'Ubuntu12.10', 'os_url': 'http://ubuntu.com/ubuntu/12.10'},
        'debian1.3': {'os_version': '1.3', 'name': 'DebianBo', 'os_url': 'http://debian.org/debian/1.3'},
        'debian1.2': {'os_version': '1.2', 'name': 'DebianRex', 'os_url': 'http://debian.org/debian/1.2'},
        'debian1.0': {'os_version': '1.1', 'name': 'DebianBuzz', 'os_url': 'http://debian.org/debian/1.0'},
        'mandriva2006.0': {'os_version': '2006.0', 'name': 'MandrivaLinux2006.0',
                           'os_url': 'http://mandriva.com/mandriva/2006.0'},
        'rhl5.2': {'os_version': '5.2', 'name': 'RedHatLinux5.2', 'os_url': 'http://redhat.com/rhl/5.2'},
        'rhl5.1': {'os_version': '5.1', 'name': 'RedHatLinux5.1', 'os_url': 'http://redhat.com/rhl/5.1'},
        'rhl5.0': {'os_version': '5.0', 'name': 'RedHatLinux5.0', 'os_url': 'http://redhat.com/rhl/5.0'},
        'centos6.5': {'os_version': '6.5', 'name': 'CentOS6.5', 'os_url': 'http://centos.org/centos/6.5'},
        'centos6.4': {'os_version': '6.4', 'name': 'CentOS6.4', 'os_url': 'http://centos.org/centos/6.4'},
        'centos6.1': {'os_version': '6.1', 'name': 'CentOS6.1', 'os_url': 'http://centos.org/centos/6.1'},
        'centos6.0': {'os_version': '6.0', 'name': 'CentOS6.0', 'os_url': 'http://centos.org/centos/6.0'},
        'centos6.3': {'os_version': '6.3', 'name': 'CentOS6.3', 'os_url': 'http://centos.org/centos/6.3'},
        'centos6.2': {'os_version': '6.2', 'name': 'CentOS6.2', 'os_url': 'http://centos.org/centos/6.2'},
        'debian3.1': {'os_version': '3.1', 'name': 'DebianSarge', 'os_url': 'http://debian.org/debian/3.1'},
        'rhel6.1': {'os_version': '6.1', 'name': 'RedHatEnterpriseLinux6.1', 'os_url': 'http://redhat.com/rhel/6.1'},
        'rhl6.2': {'os_version': '6.0', 'name': 'RedHatLinux6.2', 'os_url': 'http://redhat.com/rhl/6.2'},
        'win2k12r2': {'os_version': '6.3', 'name': 'MicrosoftWindowsServer2012R2',
                      'os_url': 'http://microsoft.com/win/2k12r2'},
        'mandriva2011': {'os_version': '2011', 'name': 'MandrivaLinux2011',
                         'os_url': 'http://mandriva.com/mandriva/2011'},
        'sles12': {'os_version': '12', 'name': 'SUSELinuxEnterpriseServer12', 'os_url': 'http://suse.com/sles/12'},
        'freebsd5.4': {'os_version': '5.4', 'name': 'FreeBSD5.4', 'os_url': 'http://freebsd.org/freebsd/5.4'},
        'freebsd5.5': {'os_version': '5.5', 'name': 'FreeBSD5.5', 'os_url': 'http://freebsd.org/freebsd/5.5'},
        'freebsd5.2': {'os_version': '5.2', 'name': 'FreeBSD5.2', 'os_url': 'http://freebsd.org/freebsd/5.2'},
        'freebsd5.3': {'os_version': '5.3', 'name': 'FreeBSD5.3', 'os_url': 'http://freebsd.org/freebsd/5.3'},
        'freebsd5.0': {'os_version': '5.0', 'name': 'FreeBSD5.0', 'os_url': 'http://freebsd.org/freebsd/5.0'},
        'freebsd5.1': {'os_version': '5.1', 'name': 'FreeBSD5.1', 'os_url': 'http://freebsd.org/freebsd/5.1'},
        'openbsd5.4': {'os_version': '5.4', 'name': 'OpenBSD5.4', 'os_url': 'http://openbsd.org/openbsd/5.4'},
        'openbsd5.5': {'os_version': '5.5', 'name': 'OpenBSD5.5', 'os_url': 'http://openbsd.org/openbsd/5.5'},
        'openbsd5.6': {'os_version': '5.6', 'name': 'OpenBSD5.6', 'os_url': 'http://openbsd.org/openbsd/5.6'},
        'openbsd5.0': {'os_version': '5.0', 'name': 'OpenBSD5.0', 'os_url': 'http://openbsd.org/openbsd/5.0'},
        'mandrake5.2': {'os_version': '5.2', 'name': 'MandrakeLinux5.2', 'os_url': 'http://mandriva.com/mandrake/5.2'},
        'openbsd5.2': {'os_version': '5.2', 'name': 'OpenBSD5.2', 'os_url': 'http://openbsd.org/openbsd/5.2'},
        'openbsd5.3': {'os_version': '5.3', 'name': 'OpenBSD5.3', 'os_url': 'http://openbsd.org/openbsd/5.3'},
        'rhel3.2': {'os_version': '3.2', 'name': 'RedHatEnterpriseLinux3Update2',
                    'os_url': 'http://redhat.com/rhel/3.2'},
        'mandrake9.1': {'os_version': '9.1', 'name': 'MandrakeLinux9.1', 'os_url': 'http://mandriva.com/mandrake/9.1'},
        'mandrake9.0': {'os_version': '9.0', 'name': 'MandrakeLinux9.0', 'os_url': 'http://mandriva.com/mandrake/9.0'},
        'mandrake9.2': {'os_version': '9.2', 'name': 'MandrakeLinux9.2', 'os_url': 'http://mandriva.com/mandrake/9.2'},
        'sles10': {'os_version': '10', 'name': 'SUSELinuxEnterpriseServer10', 'os_url': 'http://suse.com/sles/10'},
        'sles11': {'os_version': '11', 'name': 'SUSELinuxEnterpriseServer11', 'os_url': 'http://suse.com/sles/11'},
        'freebsd2.2.9': {'os_version': '2.2.9', 'name': 'FreeBSD2.2.9', 'os_url': 'http://freebsd.org/freebsd/2.2.9'},
        'freebsd2.2.8': {'os_version': '2.2.8', 'name': 'FreeBSD2.2.8', 'os_url': 'http://freebsd.org/freebsd/2.2.8'},
        'win2.0': {'os_version': '2.0', 'name': 'MicrosoftWindows2.0', 'os_url': 'http://microsoft.com/win/2.0'},
        'ubuntu6.10': {'os_version': '6.10', 'name': 'Ubuntu6.10', 'os_url': 'http://ubuntu.com/ubuntu/6.10'},
        'ubuntu11.04': {'os_version': '11.04', 'name': 'Ubuntu11.04', 'os_url': 'http://ubuntu.com/ubuntu/11.04'},
        'winxp': {'os_version': '5.1', 'name': 'MicrosoftWindowsXP', 'os_url': 'http://microsoft.com/win/xp'},
        'opensuse12.3': {'os_version': '12.3', 'name': 'openSUSE12.3', 'os_url': 'http://opensuse.org/opensuse/12.3'},
        'opensuse12.2': {'os_version': '12.2', 'name': 'openSUSE12.2', 'os_url': 'http://opensuse.org/opensuse/12.2'},
        'opensuse12.1': {'os_version': '12.1', 'name': 'openSUSE12.1', 'os_url': 'http://opensuse.org/opensuse/12.1'},
        'sled12': {'os_version': '12', 'name': 'SUSELinuxEnterpriseDesktop12', 'os_url': 'http://suse.com/sled/12'},
        'winnt3.5': {'os_version': '3.5', 'name': 'MicrosoftWindowsNTServer3.5',
                     'os_url': 'http://microsoft.com/winnt/3.5'},
        'ubuntu8.04': {'os_version': '8.04', 'name': 'Ubuntu8.04LTS', 'os_url': 'http://ubuntu.com/ubuntu/8.04'},
        'freebsd2.0': {'os_version': '2.0', 'name': 'FreeBSD2.0', 'os_url': 'http://freebsd.org/freebsd/2.0'},
        'rhel4.6': {'os_version': '4.6', 'name': 'RedHatEnterpriseLinux4.6', 'os_url': 'http://redhat.com/rhel/4.6'},
        'rhel4.7': {'os_version': '4.7', 'name': 'RedHatEnterpriseLinux4.7', 'os_url': 'http://redhat.com/rhel/4.7'},
        'rhel4.4': {'os_version': '4.4', 'name': 'RedHatEnterpriseLinux4.4', 'os_url': 'http://redhat.com/rhel/4.4'},
        'rhel4.5': {'os_version': '4.5', 'name': 'RedHatEnterpriseLinux4.5', 'os_url': 'http://redhat.com/rhel/4.5'},
        'rhel4.2': {'os_version': '4.2', 'name': 'RedHatEnterpriseLinux4.2', 'os_url': 'http://redhat.com/rhel/4.2'},
        'rhel4.3': {'os_version': '4.3', 'name': 'RedHatEnterpriseLinux4.3', 'os_url': 'http://redhat.com/rhel/4.3'},
        'rhel4.0': {'os_version': '4.0', 'name': 'RedHatEnterpriseLinux4.0', 'os_url': 'http://redhat.com/rhel/4.0'},
        'rhel4.1': {'os_version': '4.1', 'name': 'RedHatEnterpriseLinux4.1', 'os_url': 'http://redhat.com/rhel/4.1'},
        'rhel4.8': {'os_version': '4.8', 'name': 'RedHatEnterpriseLinux4.8', 'os_url': 'http://redhat.com/rhel/4.8'},
        'rhel4.9': {'os_version': '4.9', 'name': 'RedHatEnterpriseLinux4.9', 'os_url': 'http://redhat.com/rhel/4.9'},
        'fedora10': {'os_version': '10', 'name': 'Fedora10', 'os_url': 'http://fedoraproject.org/fedora/10'},
        'fedora11': {'os_version': '11', 'name': 'Fedora11', 'os_url': 'http://fedoraproject.org/fedora/11'},
        'fedora12': {'os_version': '12', 'name': 'Fedora12', 'os_url': 'http://fedoraproject.org/fedora/12'},
        'fedora13': {'os_version': '13', 'name': 'Fedora13', 'os_url': 'http://fedoraproject.org/fedora/13'},
        'fedora14': {'os_version': '14', 'name': 'Fedora14', 'os_url': 'http://fedoraproject.org/fedora/14'},
        'fedora15': {'os_version': '15', 'name': 'Fedora15', 'os_url': 'http://fedoraproject.org/fedora/15'},
        'fedora16': {'os_version': '16', 'name': 'Fedora16', 'os_url': 'http://fedoraproject.org/fedora/16'},
        'fedora17': {'os_version': '17', 'name': 'Fedora17', 'os_url': 'http://fedoraproject.org/fedora/17'},
        'freebsd6.1': {'os_version': '6.1', 'name': 'FreeBSD6.1', 'os_url': 'http://freebsd.org/freebsd/6.1'},
        'freebsd6.0': {'os_version': '6.0', 'name': 'FreeBSD6.0', 'os_url': 'http://freebsd.org/freebsd/6.0'},
        'freebsd6.3': {'os_version': '6.3', 'name': 'FreeBSD6.3', 'os_url': 'http://freebsd.org/freebsd/6.3'},
        'freebsd6.2': {'os_version': '6.2', 'name': 'FreeBSD6.2', 'os_url': 'http://freebsd.org/freebsd/6.2'},
        'freebsd6.4': {'os_version': '6.4', 'name': 'FreeBSD6.4', 'os_url': 'http://freebsd.org/freebsd/6.4'},
        'ubuntu7.10': {'os_version': '7.10', 'name': 'Ubuntu7.10', 'os_url': 'http://ubuntu.com/ubuntu/7.10'},
        'opensuse10.3': {'os_version': '10.3', 'name': 'openSUSE10.3', 'os_url': 'http://opensuse.org/opensuse/10.3'},
        'opensuse10.2': {'os_version': '10.2', 'name': 'openSUSE10.2', 'os_url': 'http://opensuse.org/opensuse/10.2'},
        'altlinux6': {'os_version': '6.0', 'name': 'ALTLinux6.0.0Centaurus',
                      'os_url': 'http://altlinux.org/altlinux/6'},
        'altlinux7': {'os_version': '7.0', 'name': 'ALTLinux7.0.0Centaurus',
                      'os_url': 'http://altlinux.org/altlinux/7'},
        'altlinux5': {'os_version': '5.0', 'name': 'ALTLinux5.0.0Ark', 'os_url': 'http://altlinux.org/altlinux/5'},
        'debian2.0': {'os_version': '2.0', 'name': 'DebianHamm', 'os_url': 'http://debian.org/debian/2.0'},
        'winnt3.51': {'os_version': '3.51', 'name': 'MicrosoftWindowsNTServer3.51',
                      'os_url': 'http://microsoft.com/winnt/3.51'},
        'sles11sp4': {'os_version': '11.4', 'name': 'SUSELinuxEnterpriseServer11SP4',
                      'os_url': 'http://suse.com/sles/11.4'},
        'debian2.1': {'os_version': '2.1', 'name': 'DebianSlink', 'os_url': 'http://debian.org/debian/2.1'},
        'macosx10.2': {'os_version': '10.2', 'name': 'MacOSXJaguar', 'os_url': 'http://apple.com/macosx/10.2'},
        'macosx10.3': {'os_version': '10.3', 'name': 'MacOSXPanther', 'os_url': 'http://apple.com/macosx/10.3'},
        'macosx10.0': {'os_version': '10.0', 'name': 'MacOSXCheetah', 'os_url': 'http://apple.com/macosx/10.0'},
        'macosx10.1': {'os_version': '10.1', 'name': 'MacOSXPuma', 'os_url': 'http://apple.com/macosx/10.1'},
        'macosx10.6': {'os_version': '10.6', 'name': 'MacOSXSnowLeopard', 'os_url': 'http://apple.com/macosx/10.6'},
        'debian2.2': {'os_version': '2.2', 'name': 'DebianPotato', 'os_url': 'http://debian.org/debian/2.2'},
        'macosx10.4': {'os_version': '10.4', 'name': 'MacOSXTiger', 'os_url': 'http://apple.com/macosx/10.4'},
        'macosx10.5': {'os_version': '10.5', 'name': 'MacOSXLeopard', 'os_url': 'http://apple.com/macosx/10.5'},
        'centos7.0': {'os_version': '7.0', 'name': 'CentOS7.0', 'os_url': 'http://centos.org/centos/7.0'},
        'altlinux3.0': {'os_version': '3.0', 'name': 'ALTLinux3.0', 'os_url': 'http://altlinux.org/altlinux/3.0'},
        'rhel6.3': {'os_version': '6.3', 'name': 'RedHatEnterpriseLinux6.3', 'os_url': 'http://redhat.com/rhel/6.3'},
        'win95': {'os_version': '4.0', 'name': 'MicrosoftWindows95', 'os_url': 'http://microsoft.com/win/95'},
        'winnt3.1': {'os_version': '3.1', 'name': 'MicrosoftWindowsNTServer3.1',
                     'os_url': 'http://microsoft.com/winnt/3.1'},
        'ubuntu16.04': {'os_version': '16.04', 'name': 'Ubuntu16.04', 'os_url': 'http://ubuntu.com/ubuntu/16.04'},
        'freebsd4.9': {'os_version': '4.9', 'name': 'FreeBSD4.9', 'os_url': 'http://freebsd.org/freebsd/4.9'},
        'freebsd4.8': {'os_version': '4.8', 'name': 'FreeBSD4.8', 'os_url': 'http://freebsd.org/freebsd/4.8'},
        'rhl7.1': {'os_version': '7.1', 'name': 'RedHatLinux7.1', 'os_url': 'http://redhat.com/rhl/7.1'},
        'rhl9': {'os_version': '9', 'name': 'RedHatLinux9', 'os_url': 'http://redhat.com/rhl/9'},
        'rhl7.3': {'os_version': '7.3', 'name': 'RedHatLinux7.3', 'os_url': 'http://redhat.com/rhl/7.3'},
        'rhl7.2': {'os_version': '7.2', 'name': 'RedHatLinux7.2', 'os_url': 'http://redhat.com/rhl/7.2'},
        'freebsd4.3': {'os_version': '4.3', 'name': 'FreeBSD4.3', 'os_url': 'http://freebsd.org/freebsd/4.3'},
        'freebsd5.2.1': {'os_version': '5.2.1', 'name': 'FreeBSD5.2.1', 'os_url': 'http://freebsd.org/freebsd/5.2.1'},
        'freebsd4.1': {'os_version': '4.1', 'name': 'FreeBSD4.1', 'os_url': 'http://freebsd.org/freebsd/4.1'},
        'freebsd4.0': {'os_version': '4.0', 'name': 'FreeBSD4.0', 'os_url': 'http://freebsd.org/freebsd/4.0'},
        'freebsd4.7': {'os_version': '4.7', 'name': 'FreeBSD4.7', 'os_url': 'http://freebsd.org/freebsd/4.7'},
        'freebsd4.6': {'os_version': '4.6', 'name': 'FreeBSD4.6', 'os_url': 'http://freebsd.org/freebsd/4.6'},
        'freebsd4.5': {'os_version': '4.5', 'name': 'FreeBSD4.5', 'os_url': 'http://freebsd.org/freebsd/4.5'},
        'freebsd4.4': {'os_version': '4.4', 'name': 'FreeBSD4.4', 'os_url': 'http://freebsd.org/freebsd/4.4'},
        'ubuntu14.10': {'os_version': '14.10', 'name': 'Ubuntu14.10', 'os_url': 'http://ubuntu.com/ubuntu/14.10'},
        'rhl7': {'os_version': '7', 'name': 'RedHatLinux7', 'os_url': 'http://redhat.com/rhl/7'},
        'altlinux4.0': {'os_version': '4.0', 'name': 'ALTLinux4.0', 'os_url': 'http://altlinux.org/altlinux/4.0'},
        'altlinux4.1': {'os_version': '4.1', 'name': 'ALTLinux4.1', 'os_url': 'http://altlinux.org/altlinux/4.1'},
        'openbsd4.5': {'os_version': '4.5', 'name': 'OpenBSD4.5', 'os_url': 'http://openbsd.org/openbsd/4.5'},
        'mbs1.0': {'os_version': '1.0', 'name': 'MandrivaBusinessServer1.0', 'os_url': 'http://mandriva.com/mbs/1.0'},
        'mandrake8.0': {'os_version': '8.0', 'name': 'MandrakeLinux8.0', 'os_url': 'http://mandriva.com/mandrake/8.0'},
        'mandrake8.1': {'os_version': '8.1', 'name': 'MandrakeLinux8.1', 'os_url': 'http://mandriva.com/mandrake/8.1'},
        'mandrake8.2': {'os_version': '8.2', 'name': 'MandrakeLinux8.2', 'os_url': 'http://mandriva.com/mandrake/8.2'},
        'mandrake5.1': {'os_version': '5.1', 'name': 'MandrakeLinux5.1', 'os_url': 'http://mandriva.com/mandrake/5.1'},
        'openbsd4.4': {'os_version': '4.4', 'name': 'OpenBSD4.4', 'os_url': 'http://openbsd.org/openbsd/4.4'},
        'mandriva2010.1': {'os_version': '2010.1', 'name': 'MandrivaLinux2010Spring',
                           'os_url': 'http://mandriva.com/mandriva/2010.1'},
        'mandriva2010.0': {'os_version': '2010.0', 'name': 'MandrivaLinux2010',
                           'os_url': 'http://mandriva.com/mandriva/2010.0'},
        'mandriva2010.2': {'os_version': '2010.2', 'name': 'MandrivaLinux2010.2',
                           'os_url': 'http://mandriva.com/mandriva/2010.2'},
        'rhl8.0': {'os_version': '8.0', 'name': 'RedHatLinux8.0', 'os_url': 'http://redhat.com/rhl/8.0'},
        'ubuntu9.10': {'os_version': '9.10', 'name': 'Ubuntu9.10', 'os_url': 'http://ubuntu.com/ubuntu/9.10'},
        'solaris10': {'os_version': '10', 'name': 'SunSolaris10', 'os_url': 'http://sun.com/solaris/10'},
        'openbsd4.3': {'os_version': '4.3', 'name': 'OpenBSD4.3', 'os_url': 'http://openbsd.org/openbsd/4.3'},
        'win3.1': {'os_version': '3.1', 'name': 'MicrosoftWindows3.1', 'os_url': 'http://microsoft.com/win/3.1'},
        'netbsd1.2': {'os_version': '1.2', 'name': 'NetBSD1.2', 'os_url': 'http://netbsd.org/netbsd/1.2'},
        'sled11sp4': {'os_version': '11.4', 'name': 'SUSELinuxEnterpriseDesktop11SP4',
                      'os_url': 'http://suse.com/sled/11.4'},
        'openbsd4.8': {'os_version': '4.8', 'name': 'OpenBSD4.8', 'os_url': 'http://openbsd.org/openbsd/4.8'},
        'sles9': {'os_version': '9', 'name': 'SUSELinuxEnterpriseServer9', 'os_url': 'http://suse.com/sles/9'},
        'freebsd4.11': {'os_version': '4.11', 'name': 'FreeBSD4.11', 'os_url': 'http://freebsd.org/freebsd/4.11'},
        'freebsd4.10': {'os_version': '4.10', 'name': 'FreeBSD4.10', 'os_url': 'http://freebsd.org/freebsd/4.10'},
        'ubuntu4.10': {'os_version': '4.10', 'name': 'Ubuntu4.10', 'os_url': 'http://ubuntu.com/ubuntu/4.10'},
        'msdos6.22': {'os_version': '6.22', 'name': 'MicrosoftMS-DOS6.22', 'os_url': 'http://microsoft.com/msdos/6.22'},
        'win1.0': {'os_version': '1.0', 'name': 'MicrosoftWindows1.0', 'os_url': 'http://microsoft.com/win/1.0'},
        'sles11sp3': {'os_version': '11.3', 'name': 'SUSELinuxEnterpriseServer11SP3',
                      'os_url': 'http://suse.com/sles/11.3'},
        'sles11sp2': {'os_version': '11.2', 'name': 'SUSELinuxEnterpriseServer11SP2',
                      'os_url': 'http://suse.com/sles/11.2'},
        'sles11sp1': {'os_version': '11.1', 'name': 'SUSELinuxEnterpriseServer11SP1',
                      'os_url': 'http://suse.com/sles/11.1'},
        'rhel2.1': {'os_version': '2.1', 'name': 'RedHatEnterpriseLinux2.1', 'os_url': 'http://redhat.com/rhel/2.1'},
        'openbsd4.2': {'os_version': '4.2', 'name': 'OpenBSD4.2', 'os_url': 'http://openbsd.org/openbsd/4.2'},
        'rhel-atomic-7.0': {'os_version': '7.0', 'name': 'RedHatEnterpriseLinuxAtomicHost7.0',
                            'os_url': 'http://redhat.com/rhel-atomic/7.0'},
        'rhl3.0.3': {'os_version': '3.0.3', 'name': 'RedHatLinux3.0.3', 'os_url': 'http://redhat.com/rhl/3.0.3'},
        'netbsd4.0': {'os_version': '4.0', 'name': 'NetBSD4.0', 'os_url': 'http://netbsd.org/netbsd/4.0'},
        'macosx10.7': {'os_version': '10.7', 'name': 'MacOSXLion', 'os_url': 'http://apple.com/macosx/10.7'},
        'rhel2.1.5': {'os_version': '2.1.5', 'name': 'RedHatEnterpriseLinux2.1Update5',
                      'os_url': 'http://redhat.com/rhel/2.1.5'},
        'rhel2.1.4': {'os_version': '2.1.4', 'name': 'RedHatEnterpriseLinux2.1Update4',
                      'os_url': 'http://redhat.com/rhel/2.1.4'},
        'rhel2.1.7': {'os_version': '2.1.7', 'name': 'RedHatEnterpriseLinux2.1Update7',
                      'os_url': 'http://redhat.com/rhel/2.1.7'},
        'rhel2.1.6': {'os_version': '2.1.6', 'name': 'RedHatEnterpriseLinux2.1Update6',
                      'os_url': 'http://redhat.com/rhel/2.1.6'},
        'rhel2.1.1': {'os_version': '2.1.1', 'name': 'RedHatEnterpriseLinux2.1Update1',
                      'os_url': 'http://redhat.com/rhel/2.1.1'},
        'win2k8r2': {'os_version': '6.1', 'name': 'MicrosoftWindowsServer2008R2',
                     'os_url': 'http://microsoft.com/win/2k8r2'},
        'rhel2.1.3': {'os_version': '2.1.3', 'name': 'RedHatEnterpriseLinux2.1Update3',
                      'os_url': 'http://redhat.com/rhel/2.1.3'},
        'rhel2.1.2': {'os_version': '2.1.2', 'name': 'RedHatEnterpriseLinux2.1Update2',
                      'os_url': 'http://redhat.com/rhel/2.1.2'},
        'ubuntu15.04': {'os_version': '15.04', 'name': 'Ubuntu15.04', 'os_url': 'http://ubuntu.com/ubuntu/15.04'},
        'win2.1': {'os_version': '2.1', 'name': 'MicrosoftWindows2.1', 'os_url': 'http://microsoft.com/win/2.1'},
        'rhel5.1': {'os_version': '5.1', 'name': 'RedHatEnterpriseLinux5.1', 'os_url': 'http://redhat.com/rhel/5.1'},
        'mageia3': {'os_version': '3', 'name': 'Mageia3', 'os_url': 'http://mageia.org/mageia/3'},
        'mageia2': {'os_version': '2', 'name': 'Mageia2', 'os_url': 'http://mageia.org/mageia/2'},
        'mageia1': {'os_version': '1', 'name': 'Mageia1', 'os_url': 'http://mageia.org/mageia/1'},
        'mes5': {'os_version': '5.0', 'name': 'MandrivaEnterpriseServer5.0', 'os_url': 'http://mandriva.com/mes/5.0'},
        'rhel6.6': {'os_version': '6.6', 'name': 'RedHatEnterpriseLinux6.6', 'os_url': 'http://redhat.com/rhel/6.6'},
        'gnome-continuous-3.14': {'os_version': '3.14', 'name': 'GNOME3.14',
                                  'os_url': 'http://gnome.org/continuous/3.14'},
        'mandriva2008.0': {'os_version': '2008.0', 'name': 'MandrivaLinux2008',
                           'os_url': 'http://mandriva.com/mandriva/2008.0'},
        'mandriva2008.1': {'os_version': '2008.1', 'name': 'MandrivaLinux2008Spring',
                           'os_url': 'http://mandriva.com/mandriva/2008.1'},
        'rhl1.1': {'os_version': '1.1', 'name': 'RedHatLinux1.1', 'os_url': 'http://redhat.com/rhl/1.1'},
        'fedora8': {'os_version': '8', 'name': 'Fedora8', 'os_url': 'http://fedoraproject.org/fedora/8'},
        'fedora9': {'os_version': '9', 'name': 'Fedora9', 'os_url': 'http://fedoraproject.org/fedora/9'},
        'fedora6': {'os_version': '6', 'name': 'FedoraCore6', 'os_url': 'http://fedoraproject.org/fedora/6'},
        'fedora7': {'os_version': '7', 'name': 'Fedora7', 'os_url': 'http://fedoraproject.org/fedora/7'},
        'fedora4': {'os_version': '4', 'name': 'FedoraCore4', 'os_url': 'http://fedoraproject.org/fedora/4'},
        'fedora5': {'os_version': '5', 'name': 'FedoraCore5', 'os_url': 'http://fedoraproject.org/fedora/5'},
        'fedora2': {'os_version': '2', 'name': 'FedoraCore2', 'os_url': 'http://fedoraproject.org/fedora/2'},
        'fedora3': {'os_version': '3', 'name': 'FedoraCore3', 'os_url': 'http://fedoraproject.org/fedora/3'},
        'gnome-continuous-3.12': {'os_version': '3.12', 'name': 'GNOME3.12',
                                  'os_url': 'http://gnome.org/continuous/3.12'},
        'fedora1': {'os_version': '1', 'name': 'FedoraCore1', 'os_url': 'http://fedoraproject.org/fedora/1'},
        'altlinux2.4': {'os_version': '2.4', 'name': 'ALTLinux2.4', 'os_url': 'http://altlinux.org/altlinux/2.4'},
        'win8': {'os_version': '6.2', 'name': 'MicrosoftWindows8', 'os_url': 'http://microsoft.com/win/8'},
        'altlinux2.0': {'os_version': '2.0', 'name': 'ALTLinux2.0', 'os_url': 'http://altlinux.org/altlinux/2.0'},
        'altlinux2.2': {'os_version': '2.2', 'name': 'ALTLinux2.2', 'os_url': 'http://altlinux.org/altlinux/2.2'},
        'mes5.1': {'os_version': '5.1', 'name': 'MandrivaEnterpriseServer5.1', 'os_url': 'http://mandriva.com/mes/5.1'},
        'fedora21': {'os_version': '21', 'name': 'Fedora21', 'os_url': 'http://fedoraproject.org/fedora/21'},
        'fedora20': {'os_version': '20', 'name': 'Fedora20', 'os_url': 'http://fedoraproject.org/fedora/20'},
        'fedora22': {'os_version': '22', 'name': 'Fedora22', 'os_url': 'http://fedoraproject.org/fedora/22'},
        'sled11sp3': {'os_version': '11.3', 'name': 'SUSELinuxEnterpriseDesktop11SP3',
                      'os_url': 'http://suse.com/sled/11.3'},
        'win7': {'os_version': '6.1', 'name': 'MicrosoftWindows7', 'os_url': 'http://microsoft.com/win/7'},
        'mandriva2007.1': {'os_version': '2007.1', 'name': 'MandrivaLinux2007Spring',
                           'os_url': 'http://mandriva.com/mandriva/2007.1'},
        'winme': {'os_version': '4.9', 'name': 'MicrosoftWindowsMillenniumEdition',
                  'os_url': 'http://microsoft.com/win/me'},
        'win2k3': {'os_version': '5.2', 'name': 'MicrosoftWindowsServer2003', 'os_url': 'http://microsoft.com/win/2k3'},
        'netbsd0.9': {'os_version': '0.9', 'name': 'NetBSD0.9', 'os_url': 'http://netbsd.org/netbsd/0.9'},
        'netbsd0.8': {'os_version': '0.8', 'name': 'NetBSD0.8', 'os_url': 'http://netbsd.org/netbsd/0.8'},
        'gnome3.8': {'os_version': '3.8', 'name': 'GNOME3.8', 'os_url': 'http://gnome.org/3.8'},
        'winnt4.0': {'os_version': '4.0', 'name': 'MicrosoftWindowsNTServer4.0',
                     'os_url': 'http://microsoft.com/winnt/4.0'},
        'freebsd10.0': {'os_version': '10.0', 'name': 'FreeBSD10.0', 'os_url': 'http://freebsd.org/freebsd/10.0'},
        'rhl6.0': {'os_version': '6.0', 'name': 'RedHatLinux6.0', 'os_url': 'http://redhat.com/rhl/6.0'},
        'rhl6.1': {'os_version': '6.1', 'name': 'RedHatLinux6.1', 'os_url': 'http://redhat.com/rhl/6.1'},
        'ubuntu14.04': {'os_version': '14.04', 'name': 'Ubuntu14.04LTS', 'os_url': 'http://ubuntu.com/ubuntu/14.04'},
        'ubuntu12.04': {'os_version': '12.04', 'name': 'Ubuntu12.04LTS', 'os_url': 'http://ubuntu.com/ubuntu/12.04'},
        'fedora18': {'os_version': '18', 'name': 'Fedora18', 'os_url': 'http://fedoraproject.org/fedora/18'},
        'ubuntu5.04': {'os_version': '5.04', 'name': 'Ubuntu5.04', 'os_url': 'http://ubuntu.com/ubuntu/5.04'},
        'fedora19': {'os_version': '19', 'name': 'Fedora19', 'os_url': 'http://fedoraproject.org/fedora/19'},
        'netware6': {'os_version': '6', 'name': 'NovellNetware6', 'os_url': 'http://novell.com/netware6'},
        'netware4': {'os_version': '4', 'name': 'NovellNetware4', 'os_url': 'http://novell.com/netware4'},
        'netware5': {'os_version': '5', 'name': 'NovellNetware5', 'os_url': 'http://novell.com/netware5'},
        'mandrake5.3': {'os_version': '5.3', 'name': 'MandrakeLinux5.3', 'os_url': 'http://mandriva.com/mandrake/5.3'},
        'ubuntu9.04': {'os_version': '9.04', 'name': 'Ubuntu9.04', 'os_url': 'http://ubuntu.com/ubuntu/9.04'},
        'rhel5.6': {'os_version': '5.6', 'name': 'RedHatEnterpriseLinux5.6', 'os_url': 'http://redhat.com/rhel/5.6'},
        'solaris9': {'os_version': '9', 'name': 'SunSolaris9', 'os_url': 'http://sun.com/solaris/9'},
        'win2k3r2': {'os_version': '5.2', 'name': 'MicrosoftWindowsServer2003R2',
                     'os_url': 'http://microsoft.com/win/2k3r2'},
        'gnome3.6': {'os_version': '3.6', 'name': 'GNOME3.6', 'os_url': 'http://gnome.org/3.6'},
        'rhel3': {'os_version': '3', 'name': 'RedHatEnterpriseLinux3', 'os_url': 'http://redhat.com/rhel/3'},
        'mandrake10.2': {'os_version': '10.2', 'name': 'MandrakeLinux10.2',
                         'os_url': 'http://mandriva.com/mandrake/10.2'},
        'mandrake10.0': {'os_version': '10.0', 'name': 'MandrakeLinux10.0',
                         'os_url': 'http://mandriva.com/mandrake/10.0'},
        'mandrake10.1': {'os_version': '10.1', 'name': 'MandrakeLinux10.1',
                         'os_url': 'http://mandriva.com/mandrake/10.1'},
        'netbsd2.0': {'os_version': '2.0', 'name': 'NetBSD2.0', 'os_url': 'http://netbsd.org/netbsd/2.0'},
        'win2k': {'os_version': '5.0', 'name': 'MicrosoftWindows2000', 'os_url': 'http://microsoft.com/win/2k'},
        'ubuntu13.10': {'os_version': '13.10', 'name': 'Ubuntu13.10', 'os_url': 'http://ubuntu.com/ubuntu/13.10'},
        'opensuse-factory': {'os_version': 'factory', 'name': 'openSUSE',
                             'os_url': 'http://opensuse.org/opensuse/factory'},
        'openbsd4.9': {'os_version': '4.9', 'name': 'OpenBSD4.9', 'os_url': 'http://openbsd.org/openbsd/4.9'}}
