#!/bin/bash

pip install pysnmp==4.2.5
pip install splinter

chown -R ovs:ovs /opt/OpenvStorage/ci

find /opt/OpenvStorage -name *.pyc -exec rm -rf {} \;

wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
apt-get update
apt-get install google-chrome-beta x11vnc  libav-tools -y --force-yes
wget http://chromedriver.storage.googleapis.com/2.19/chromedriver_linux64.zip;unzip chromedriver_linux64.zip;mv chromedriver /usr/bin/
if [ ! -f /usr/lib/libudev.so.0 ]; then ln -s /lib/x86_64-linux-gnu/libudev.so.1.3.5 /usr/lib/libudev.so.0; fi

cat <<EOF >>/usr/lib/python2.7/sitecustomize.py
import sys
sys.setdefaultencoding('utf8')
EOF
echo 1

pip install vnc2flv
